part of 'country_picker.dart';

final List<Country> countryList =    [
  Country(
    isoCode: "OM",
    phoneCode: "968",
    name: "Oman",
    nameAr: "عمان",
    iso3Code: "OMN",
  ),
  Country(
    isoCode: "SA",
    phoneCode: "966",
    name: "Saudi Arabia",
    nameAr: "المملكة العربية السعودية",
    iso3Code: "SAU",
  ),
  Country(
    isoCode: "AF",
    phoneCode: "93",
    name: "Afghanistan",
    nameAr: "أفغانستان",
    iso3Code: "AFG",
  ),
  Country(
    isoCode: "AL",
    phoneCode: "355",
    name: "Albania",
    nameAr: "ألبانيا",
    iso3Code: "ALB",
  ),
  Country(
    isoCode: "DZ",
    phoneCode: "213",
    name: "Algeria",
    nameAr: "الجزائر",
    iso3Code: "DZA",
  ),
  Country(
    isoCode: "AS",
    phoneCode: "1-684",
    name: "American Samoa",
    nameAr: "ساموا الأمريكية",
    iso3Code: "ASM",
  ),
  Country(
    isoCode: "AD",
    phoneCode: "376",
    name: "Andorra",
    nameAr: "أندورا",
    iso3Code: "AND",
  ),
  Country(
    isoCode: "AO",
    phoneCode: "244",
    name: "Angola",
    nameAr: "أنغولا",
    iso3Code: "AGO",
  ),
  Country(
    isoCode: "AI",
    phoneCode: "1-264",
    name: "Anguilla",
    nameAr: "أنغويلا",
    iso3Code: "AIA",
  ),
  Country(
    isoCode: "AQ",
    phoneCode: "672",
    name: "Antarctica",
    nameAr: "أنتاركتيكا",
    iso3Code: "ATA",
  ),
  Country(
    isoCode: "AG",
    phoneCode: "1-268",
    name: "Antigua and Barbuda",
    nameAr: "أنتيغوا وباربودا",
    iso3Code: "ATG",
  ),
  Country(
    isoCode: "AR",
    phoneCode: "54",
    name: "Argentina",
    nameAr: "الأرجنتين",
    iso3Code: "ARG",
  ),
  Country(
    isoCode: "AM",
    phoneCode: "374",
    name: "Armenia",
    nameAr: "أرمينيا",
    iso3Code: "ARM",
  ),
  Country(
    isoCode: "AW",
    phoneCode: "297",
    name: "Aruba",
    nameAr: "أروبا",
    iso3Code: "ABW",
  ),
  Country(
    isoCode: "AU",
    phoneCode: "61",
    name: "Australia",
    nameAr: "أستراليا",
    iso3Code: "AUS",
  ),
  Country(
    isoCode: "AT",
    phoneCode: "43",
    name: "Austria",
    nameAr: "النمسا",
    iso3Code: "AUT",
  ),
  Country(
    isoCode: "AZ",
    phoneCode: "994",
    name: "Azerbaijan",
    nameAr: "أذربيجان",
    iso3Code: "AZE",
  ),
  Country(
    isoCode: "BS",
    phoneCode: "1-242",
    name: "Bahamas",
    nameAr: "الباهاما",
    iso3Code: "BHS",
  ),
  Country(
    isoCode: "BH",
    phoneCode: "973",
    name: "Bahrain",
    nameAr: "البحرين",
    iso3Code: "BHR",
  ),
  Country(
    isoCode: "BD",
    phoneCode: "880",
    name: "Bangladesh",
    nameAr: "بنغلاديش",
    iso3Code: "BGD",
  ),
  Country(
    isoCode: "BB",
    phoneCode: "1-246",
    name: "Barbados",
    nameAr: "باربادوس",
    iso3Code: "BRB",
  ),
  Country(
    isoCode: "BY",
    phoneCode: "375",
    name: "Belarus",
    nameAr: "بيلاروسيا",
    iso3Code: "BLR",
  ),
  Country(
    isoCode: "BE",
    phoneCode: "32",
    name: "Belgium",
    nameAr: "بلجيكا",
    iso3Code: "BEL",
  ),
  Country(
    isoCode: "BZ",
    phoneCode: "501",
    name: "Belize",
    nameAr: "بليز",
    iso3Code: "BLZ",
  ),
  Country(
    isoCode: "BJ",
    phoneCode: "229",
    name: "Benin",
    nameAr: "بنين",
    iso3Code: "BEN",
  ),
  Country(
    isoCode: "BM",
    phoneCode: "1-441",
    name: "Bermuda",
    nameAr: "برمودا",
    iso3Code: "BMU",
  ),
  Country(
    isoCode: "BT",
    phoneCode: "975",
    name: "Bhutan",
    nameAr: "بوتان",
    iso3Code: "BTN",
  ),
  Country(
    isoCode: "BO",
    phoneCode: "591",
    name: "Bolivia, Plurinational State of",
    nameAr: "بوليفيا",
    iso3Code: "BOL",
  ),
  Country(
    isoCode: "BA",
    phoneCode: "387",
    name: "Bosnia and Herzegovina",
    nameAr: "البوسنة والهرسك",
    iso3Code: "BIH",
  ),
  Country(
    isoCode: "BW",
    phoneCode: "267",
    name: "Botswana",
    nameAr: "بوتسوانا",
    iso3Code: "BWA",
  ),
  Country(
    isoCode: "BV",
    phoneCode: "47",
    name: "Bouvet Island",
    nameAr: "جزيرة بوفيه",
    iso3Code: "BVT",
  ),
  Country(
    isoCode: "BR",
    phoneCode: "55",
    name: "Brazil",
    nameAr: "البرازيل",
    iso3Code: "BRA",
  ),
  Country(
    isoCode: "IO",
    phoneCode: "246",
    name: "British Indian Ocean Territory",
    nameAr: "إقليم المحيط الهندي البريطاني",
    iso3Code: "IOT",
  ),
  Country(
    isoCode: "BN",
    phoneCode: "673",
    name: "Brunei Darussalam",
    nameAr: "بروناي",
    iso3Code: "BRN",
  ),
  Country(
    isoCode: "BG",
    phoneCode: "359",
    name: "Bulgaria",
    nameAr: "بلغاريا",
    iso3Code: "BGR",
  ),
  Country(
    isoCode: "BF",
    phoneCode: "226",
    name: "Burkina Faso",
    nameAr: "بوركينا فاسو",
    iso3Code: "BFA",
  ),
  Country(
    isoCode: "BI",
    phoneCode: "257",
    name: "Burundi",
    nameAr: "بوروندي",
    iso3Code: "BDI",
  ),
  Country(
    isoCode: "KH",
    phoneCode: "855",
    name: "Cambodia",
    nameAr: "كمبوديا",
    iso3Code: "KHM",
  ),
  Country(
    isoCode: "CM",
    phoneCode: "237",
    name: "Cameroon",
    nameAr: "الكاميرون",
    iso3Code: "CMR",
  ),
  Country(
    isoCode: "CA",
    phoneCode: "1",
    name: "Canada",
    nameAr: "كندا",
    iso3Code: "CAN",
  ),
  Country(
    isoCode: "CV",
    phoneCode: "238",
    name: "Cape Verde",
    nameAr: "الرأس الأخضر",
    iso3Code: "CPV",
  ),
  Country(
    isoCode: "BQ",
    phoneCode: "599",
    name: "Caribbean Netherlands",
    nameAr: "هولندا الكاريبية",
    iso3Code: "BES",
  ),
  Country(
    isoCode: "KY",
    phoneCode: "1-345",
    name: "Cayman Islands",
    nameAr: "جزر كايمان",
    iso3Code: "CYM",
  ),
  Country(
    isoCode: "CF",
    phoneCode: "236",
    name: "Central African Republic",
    nameAr: "جمهورية أفريقيا الوسطى",
    iso3Code: "CAF",
  ),
  Country(
    isoCode: "TD",
    phoneCode: "235",
    name: "Chad",
    nameAr: "تشاد",
    iso3Code: "TCD",
  ),
  Country(
    isoCode: "CL",
    phoneCode: "56",
    name: "Chile",
    nameAr: "تشيلي",
    iso3Code: "CHL",
  ),
  Country(
    isoCode: "CN",
    phoneCode: "86",
    name: "China",
    nameAr: "الصين",
    iso3Code: "CHN",
  ),
  Country(
    isoCode: "CX",
    phoneCode: "61",
    name: "Christmas Island",
    nameAr: "جزيرة عيد الميلاد",
    iso3Code: "CXR",
  ),
  Country(
    isoCode: "CC",
    phoneCode: "61",
    name: "Cocos (Keeling) Islands",
    nameAr: "جزر كوكوس",
    iso3Code: "CCK",
  ),
  Country(
    isoCode: "CO",
    phoneCode: "57",
    name: "Colombia",
    nameAr: "كولومبيا",
    iso3Code: "COL",
  ),
  Country(
    isoCode: "KM",
    phoneCode: "269",
    name: "Comoros",
    nameAr: "جزر القمر",
    iso3Code: "COM",
  ),
  Country(
    isoCode: "CG",
    phoneCode: "242",
    name: "Congo",
    nameAr: "الكونغو",
    iso3Code: "COG",
  ),
  Country(
    isoCode: "CD",
    phoneCode: "243",
    name: "Congo, the Democratic Republic of the",
    nameAr: "جمهورية الكونغو الديمقراطية",
    iso3Code: "COD",
  ),
  Country(
    isoCode: "CK",
    phoneCode: "682",
    name: "Cook Islands",
    nameAr: "جزر كوك",
    iso3Code: "COK",
  ),
  Country(
    isoCode: "CR",
    phoneCode: "506",
    name: "Costa Rica",
    nameAr: "كوستاريكا",
    iso3Code: "CRI",
  ),
  Country(
    isoCode: "HR",
    phoneCode: "385",
    name: "Croatia",
    nameAr: "كرواتيا",
    iso3Code: "HRV",
  ),
  Country(
    isoCode: "CU",
    phoneCode: "53",
    name: "Cuba",
    nameAr: "كوبا",
    iso3Code: "CUB",
  ),
  Country(
    isoCode: "CW",
    phoneCode: "599",
    name: "Curaçao",
    nameAr: "كوراساو",
    iso3Code: "CUW",
  ),
  Country(
    isoCode: "CY",
    phoneCode: "357",
    name: "Cyprus",
    nameAr: "قبرص",
    iso3Code: "CYP",
  ),
  Country(
    isoCode: "CZ",
    phoneCode: "420",
    name: "Czech Republic",
    nameAr: "جمهورية التشيك",
    iso3Code: "CZE",
  ),
  Country(
    isoCode: "CI",
    phoneCode: "225",
    name: "Côte d'Ivoire",
    nameAr: "ساحل العاج",
    iso3Code: "CIV",
  ),
  Country(
    isoCode: "DK",
    phoneCode: "45",
    name: "Denmark",
    nameAr: "الدنمارك",
    iso3Code: "DNK",
  ),
  Country(
    isoCode: "DJ",
    phoneCode: "253",
    name: "Djibouti",
    nameAr: "جيبوتي",
    iso3Code: "DJI",
  ),
  Country(
    isoCode: "DM",
    phoneCode: "1-767",
    name: "Dominica",
    nameAr: "دومينيكا",
    iso3Code: "DMA",
  ),
  Country(
    isoCode: "DO",
    phoneCode: "1-849",
    name: "Dominican Republic",
    nameAr: "جمهورية الدومينيكان",
    iso3Code: "DOM",
  ),
  Country(
    isoCode: "EC",
    phoneCode: "593",
    name: "Ecuador",
    nameAr: "الإكوادور",
    iso3Code: "ECU",
  ),
  Country(
    isoCode: "EG",
    phoneCode: "20",
    name: "Egypt",
    nameAr: "مصر",
    iso3Code: "EGY",
  ),
  Country(
    isoCode: "SV",
    phoneCode: "503",
    name: "El Salvador",
    nameAr: "السلفادور",
    iso3Code: "SLV",
  ),
  Country(
    isoCode: "GB-ENG",
    phoneCode: "44",
    name: "England",
    nameAr: "إنجلترا",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "GQ",
    phoneCode: "240",
    name: "Equatorial Guinea",
    nameAr: "غينيا الاستوائية",
    iso3Code: "GNQ",
  ),
  Country(
    isoCode: "ER",
    phoneCode: "291",
    name: "Eritrea",
    nameAr: "إريتريا",
    iso3Code: "ERI",
  ),
  Country(
    isoCode: "EE",
    phoneCode: "372",
    name: "Estonia",
    nameAr: "إستونيا",
    iso3Code: "EST",
  ),
  Country(
    isoCode: "ET",
    phoneCode: "251",
    name: "Ethiopia",
    nameAr: "إثيوبيا",
    iso3Code: "ETH",
  ),
  Country(
    isoCode: "FK",
    phoneCode: "500",
    name: "Falkland Islands (Malvinas)",
    nameAr: "جزر فوكلاند",
    iso3Code: "FLK",
  ),
  Country(
    isoCode: "FO",
    phoneCode: "298",
    name: "Faroe Islands",
    nameAr: "جزر فارو",
    iso3Code: "FRO",
  ),
  Country(
    isoCode: "FJ",
    phoneCode: "679",
    name: "Fiji",
    nameAr: "فيجي",
    iso3Code: "FJI",
  ),
  Country(
    isoCode: "FI",
    phoneCode: "358",
    name: "Finland",
    nameAr: "فنلندا",
    iso3Code: "FIN",
  ),
  Country(
    isoCode: "FR",
    phoneCode: "33",
    name: "France",
    nameAr: "فرنسا",
    iso3Code: "FRA",
  ),
  Country(
    isoCode: "GF",
    phoneCode: "594",
    name: "French Guiana",
    nameAr: "غويانا الفرنسية",
    iso3Code: "GUF",
  ),
  Country(
    isoCode: "PF",
    phoneCode: "689",
    name: "French Polynesia",
    nameAr: "بولينيزيا الفرنسية",
    iso3Code: "PYF",
  ),
  Country(
    isoCode: "TF",
    phoneCode: "262",
    name: "French Southern Territories",
    nameAr: "الأراضي الجنوبية الفرنسية",
    iso3Code: "ATF",
  ),
  Country(
    isoCode: "GA",
    phoneCode: "241",
    name: "Gabon",
    nameAr: "الغابون",
    iso3Code: "GAB",
  ),
  Country(
    isoCode: "GM",
    phoneCode: "220",
    name: "Gambia",
    nameAr: "غامبيا",
    iso3Code: "GMB",
  ),
  Country(
    isoCode: "GE",
    phoneCode: "995",
    name: "Georgia",
    nameAr: "جورجيا",
    iso3Code: "GEO",
  ),
  Country(
    isoCode: "DE",
    phoneCode: "49",
    name: "Germany",
    nameAr: "ألمانيا",
    iso3Code: "DEU",
  ),
  Country(
    isoCode: "GH",
    phoneCode: "233",
    name: "Ghana",
    nameAr: "غانا",
    iso3Code: "GHA",
  ),
  Country(
    isoCode: "GI",
    phoneCode: "350",
    name: "Gibraltar",
    nameAr: "جبل طارق",
    iso3Code: "GIB",
  ),
  Country(
    isoCode: "GR",
    phoneCode: "30",
    name: "Greece",
    nameAr: "اليونان",
    iso3Code: "GRC",
  ),
  Country(
    isoCode: "GL",
    phoneCode: "299",
    name: "Greenland",
    nameAr: "جرينلاند",
    iso3Code: "GRL",
  ),
  Country(
    isoCode: "GD",
    phoneCode: "1-473",
    name: "Grenada",
    nameAr: "غرينادا",
    iso3Code: "GRD",
  ),
  Country(
    isoCode: "GP",
    phoneCode: "590",
    name: "Guadeloupe",
    nameAr: "غوادلوب",
    iso3Code: "GLP",
  ),
  Country(
    isoCode: "GU",
    phoneCode: "1-671",
    name: "Guam",
    nameAr: "غوام",
    iso3Code: "GUM",
  ),
  Country(
    isoCode: "GT",
    phoneCode: "502",
    name: "Guatemala",
    nameAr: "غواتيمالا",
    iso3Code: "GTM",
  ),
  Country(
    isoCode: "GG",
    phoneCode: "44-1481",
    name: "Guernsey",
    nameAr: "غيرنزي",
    iso3Code: "GGY",
  ),
  Country(
    isoCode: "GN",
    phoneCode: "224",
    name: "Guinea",
    nameAr: "غينيا",
    iso3Code: "GIN",
  ),
  Country(
    isoCode: "GW",
    phoneCode: "245",
    name: "Guinea-Bissau",
    nameAr: "غينيا بيساو",
    iso3Code: "GNB",
  ),
  Country(
    isoCode: "GY",
    phoneCode: "592",
    name: "Guyana",
    nameAr: "غيانا",
    iso3Code: "GUY",
  ),
  Country(
    isoCode: "HT",
    phoneCode: "509",
    name: "Haiti",
    nameAr: "هايتي",
    iso3Code: "HTI",
  ),
  Country(
    isoCode: "HM",
    phoneCode: "672",
    name: "Heard Island and McDonald Islands",
    nameAr: "جزيرة هيرد وجزر ماكدونالد",
    iso3Code: "HMD",
  ),
  Country(
    isoCode: "VA",
    phoneCode: "379",
    name: "Holy See (Vatican City State)",
    nameAr: "الفاتيكان",
    iso3Code: "VAT",
  ),
  Country(
    isoCode: "HN",
    phoneCode: "504",
    name: "Honduras",
    nameAr: "هندوراس",
    iso3Code: "HND",
  ),
  Country(
    isoCode: "HK",
    phoneCode: "852",
    name: "Hong Kong",
    nameAr: "هونغ كونغ",
    iso3Code: "HKG",
  ),
  Country(
    isoCode: "HU",
    phoneCode: "36",
    name: "Hungary",
    nameAr: "المجر",
    iso3Code: "HUN",
  ),
  Country(
    isoCode: "IS",
    phoneCode: "354",
    name: "Iceland",
    nameAr: "آيسلندا",
    iso3Code: "ISL",
  ),
  Country(
    isoCode: "IN",
    phoneCode: "91",
    name: "India",
    nameAr: "الهند",
    iso3Code: "IND",
  ),
  Country(
    isoCode: "ID",
    phoneCode: "62",
    name: "Indonesia",
    nameAr: "إندونيسيا",
    iso3Code: "IDN",
  ),
  Country(
    isoCode: "IR",
    phoneCode: "98",
    name: "Iran, Islamic Republic of",
    nameAr: "إيران",
    iso3Code: "IRN",
  ),
  Country(
    isoCode: "IQ",
    phoneCode: "964",
    name: "Iraq",
    nameAr: "العراق",
    iso3Code: "IRQ",
  ),
  Country(
    isoCode: "IE",
    phoneCode: "353",
    name: "Ireland",
    nameAr: "أيرلندا",
    iso3Code: "IRL",
  ),
  Country(
    isoCode: "IM",
    phoneCode: "44-1624",
    name: "Isle of Man",
    nameAr: "جزيرة مان",
    iso3Code: "IMN",
  ),
  Country(
    isoCode: "IT",
    phoneCode: "39",
    name: "Italy",
    nameAr: "إيطاليا",
    iso3Code: "ITA",
  ),
  Country(
    isoCode: "JM",
    phoneCode: "1-876",
    name: "Jamaica",
    nameAr: "جامايكا",
    iso3Code: "JAM",
  ),
  Country(
    isoCode: "JP",
    phoneCode: "81",
    name: "Japan",
    nameAr: "اليابان",
    iso3Code: "JPN",
  ),
  Country(
    isoCode: "JE",
    phoneCode: "44-1534",
    name: "Jersey",
    nameAr: "جيرزي",
    iso3Code: "JEY",
  ),
  Country(
    isoCode: "JO",
    phoneCode: "962",
    name: "Jordan",
    nameAr: "الأردن",
    iso3Code: "JOR",
  ),
  Country(
    isoCode: "KZ",
    phoneCode: "7",
    name: "Kazakhstan",
    nameAr: "كازاخستان",
    iso3Code: "KAZ",
  ),
  Country(
    isoCode: "KE",
    phoneCode: "254",
    name: "Kenya",
    nameAr: "كينيا",
    iso3Code: "KEN",
  ),
  Country(
    isoCode: "KI",
    phoneCode: "686",
    name: "Kiribati",
    nameAr: "كيريباتي",
    iso3Code: "KIR",
  ),
  Country(
    isoCode: "KP",
    phoneCode: "850",
    name: "Korea, Democratic People's Republic of",
    nameAr: "كوريا الشمالية",
    iso3Code: "PRK",
  ),
  Country(
    isoCode: "KR",
    phoneCode: "82",
    name: "Korea, Republic of",
    nameAr: "كوريا الجنوبية",
    iso3Code: "KOR",
  ),
  Country(
    isoCode: "XK",
    phoneCode: "383",
    name: "Kosovo",
    nameAr: "كوسوفو",
    iso3Code: "KOS",
  ),
  Country(
    isoCode: "KW",
    phoneCode: "965",
    name: "Kuwait",
    nameAr: "الكويت",
    iso3Code: "KWT",
  ),
  Country(
    isoCode: "KG",
    phoneCode: "996",
    name: "Kyrgyzstan",
    nameAr: "قيرغيزستان",
    iso3Code: "KGZ",
  ),
  Country(
    isoCode: "LA",
    phoneCode: "856",
    name: "Lao People's Democratic Republic",
    nameAr: "لاوس",
    iso3Code: "LAO",
  ),
  Country(
    isoCode: "LV",
    phoneCode: "371",
    name: "Latvia",
    nameAr: "لاتفيا",
    iso3Code: "LVA",
  ),
  Country(
    isoCode: "LB",
    phoneCode: "961",
    name: "Lebanon",
    nameAr: "لبنان",
    iso3Code: "LBN",
  ),
  Country(
    isoCode: "LS",
    phoneCode: "266",
    name: "Lesotho",
    nameAr: "ليسوتو",
    iso3Code: "LSO",
  ),
  Country(
    isoCode: "LR",
    phoneCode: "231",
    name: "Liberia",
    nameAr: "ليبيريا",
    iso3Code: "LBR",
  ),
  Country(
    isoCode: "LY",
    phoneCode: "218",
    name: "Libya",
    nameAr: "ليبيا",
    iso3Code: "LBY",
  ),
  Country(
    isoCode: "LI",
    phoneCode: "423",
    name: "Liechtenstein",
    nameAr: "ليختنشتاين",
    iso3Code: "LIE",
  ),
  Country(
    isoCode: "LT",
    phoneCode: "370",
    name: "Lithuania",
    nameAr: "ليتوانيا",
    iso3Code: "LTU",
  ),
  Country(
    isoCode: "LU",
    phoneCode: "352",
    name: "Luxembourg",
    nameAr: "لوكسمبورغ",
    iso3Code: "LUX",
  ),
  Country(
    isoCode: "MO",
    phoneCode: "853",
    name: "Macao",
    nameAr: "ماكاو",
    iso3Code: "MAC",
  ),
  Country(
    isoCode: "MK",
    phoneCode: "389",
    name: "Macedonia, the former Yugoslav Republic of",
    nameAr: "مقدونيا",
    iso3Code: "MKD",
  ),
  Country(
    isoCode: "MG",
    phoneCode: "261",
    name: "Madagascar",
    nameAr: "مدغشقر",
    iso3Code: "MDG",
  ),
  Country(
    isoCode: "MW",
    phoneCode: "265",
    name: "Malawi",
    nameAr: "مالاوي",
    iso3Code: "MWI",
  ),
  Country(
    isoCode: "MY",
    phoneCode: "60",
    name: "Malaysia",
    nameAr: "ماليزيا",
    iso3Code: "MYS",
  ),
  Country(
    isoCode: "MV",
    phoneCode: "960",
    name: "Maldives",
    nameAr: "جزر المالديف",
    iso3Code: "MDV",
  ),
  Country(
    isoCode: "ML",
    phoneCode: "223",
    name: "Mali",
    nameAr: "مالي",
    iso3Code: "MLI",
  ),
  Country(
    isoCode: "MT",
    phoneCode: "356",
    name: "Malta",
    nameAr: "مالطا",
    iso3Code: "MLT",
  ),
  Country(
    isoCode: "MH",
    phoneCode: "692",
    name: "Marshall Islands",
    nameAr: "جزر مارشال",
    iso3Code: "MHL",
  ),
  Country(
    isoCode: "MQ",
    phoneCode: "596",
    name: "Martinique",
    nameAr: "مارتينيك",
    iso3Code: "MTQ",
  ),
  Country(
    isoCode: "MR",
    phoneCode: "222",
    name: "Mauritania",
    nameAr: "موريتانيا",
    iso3Code: "MRT",
  ),
  Country(
    isoCode: "MU",
    phoneCode: "230",
    name: "Mauritius",
    nameAr: "موريشيوس",
    iso3Code: "MUS",
  ),
  Country(
    isoCode: "YT",
    phoneCode: "262",
    name: "Mayotte",
    nameAr: "مايوت",
    iso3Code: "MYT",
  ),
  Country(
    isoCode: "MX",
    phoneCode: "52",
    name: "Mexico",
    nameAr: "المكسيك",
    iso3Code: "MEX",
  ),
  Country(
    isoCode: "FM",
    phoneCode: "691",
    name: "Micronesia, Federated States of",
    nameAr: "ولايات ميكرونيسيا المتحدة",
    iso3Code: "FSM",
  ),
  Country(
    isoCode: "MD",
    phoneCode: "373",
    name: "Moldova, Republic of",
    nameAr: "مولدوفا",
    iso3Code: "MDA",
  ),
  Country(
    isoCode: "MC",
    phoneCode: "377",
    name: "Monaco",
    nameAr: "موناكو",
    iso3Code: "MCO",
  ),
  Country(
    isoCode: "MN",
    phoneCode: "976",
    name: "Mongolia",
    nameAr: "منغوليا",
    iso3Code: "MNG",
  ),
  Country(
    isoCode: "ME",
    phoneCode: "382",
    name: "Montenegro",
    nameAr: "الجبل الأسود",
    iso3Code: "MNE",
  ),
  Country(
    isoCode: "MS",
    phoneCode: "1-664",
    name: "Montserrat",
    nameAr: "مونتسرات",
    iso3Code: "MSR",
  ),
  Country(
    isoCode: "MA",
    phoneCode: "212",
    name: "Morocco",
    nameAr: "المغرب",
    iso3Code: "MAR",
  ),
  Country(
    isoCode: "MZ",
    phoneCode: "258",
    name: "Mozambique",
    nameAr: "موزمبيق",
    iso3Code: "MOZ",
  ),
  Country(
    isoCode: "MM",
    phoneCode: "95",
    name: "Myanmar",
    nameAr: "ميانمار",
    iso3Code: "MMR",
  ),
  Country(
    isoCode: "NA",
    phoneCode: "264",
    name: "Namibia",
    nameAr: "ناميبيا",
    iso3Code: "NAM",
  ),
  Country(
    isoCode: "NR",
    phoneCode: "674",
    name: "Nauru",
    nameAr: "ناورو",
    iso3Code: "NRU",
  ),
  Country(
    isoCode: "NP",
    phoneCode: "977",
    name: "Nepal",
    nameAr: "نيبال",
    iso3Code: "NPL",
  ),
  Country(
    isoCode: "NL",
    phoneCode: "31",
    name: "Netherlands",
    nameAr: "هولندا",
    iso3Code: "NLD",
  ),
  Country(
    isoCode: "AN",
    phoneCode: "599",
    name: "Netherlands Antilles",
    nameAr: "جزر الأنتيل الهولندية",
    iso3Code: "AN",
  ),
  Country(
    isoCode: "NC",
    phoneCode: "687",
    name: "New Caledonia",
    nameAr: "كاليدونيا الجديدة",
    iso3Code: "NCL",
  ),
  Country(
    isoCode: "NZ",
    phoneCode: "64",
    name: "New Zealand",
    nameAr: "نيوزيلندا",
    iso3Code: "NZL",
  ),
  Country(
    isoCode: "NI",
    phoneCode: "505",
    name: "Nicaragua",
    nameAr: "نيكاراغوا",
    iso3Code: "NIC",
  ),
  Country(
    isoCode: "NE",
    phoneCode: "227",
    name: "Niger",
    nameAr: "النيجر",
    iso3Code: "NER",
  ),
  Country(
    isoCode: "NG",
    phoneCode: "234",
    name: "Nigeria",
    nameAr: "نيجيريا",
    iso3Code: "NGA",
  ),
  Country(
    isoCode: "NU",
    phoneCode: "683",
    name: "Niue",
    nameAr: "نييوي",
    iso3Code: "NIU",
  ),
  Country(
    isoCode: "NF",
    phoneCode: "672",
    name: "Norfolk Island",
    nameAr: "جزيرة نورفولك",
    iso3Code: "NFK",
  ),
  Country(
    isoCode: "GB-NIR",
    phoneCode: "44",
    name: "Northern Ireland",
    nameAr: "أيرلندا الشمالية",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "MP",
    phoneCode: "1-670",
    name: "Northern Mariana Islands",
    nameAr: "جزر ماريانا الشمالية",
    iso3Code: "MNP",
  ),
  Country(
    isoCode: "NO",
    phoneCode: "47",
    name: "Norway",
    nameAr: "النرويج",
    iso3Code: "NOR",
  ),
  Country(
    isoCode: "PK",
    phoneCode: "92",
    name: "Pakistan",
    nameAr: "باكستان",
    iso3Code: "PAK",
  ),
  Country(
    isoCode: "PW",
    phoneCode: "680",
    name: "Palau",
    nameAr: "بالاو",
    iso3Code: "PLW",
  ),
  Country(
    isoCode: "PS",
    phoneCode: "970",
    name: "Palestine",
    nameAr: "فلسطين",
    iso3Code: "PSE",
  ),
  Country(
    isoCode: "PA",
    phoneCode: "507",
    name: "Panama",
    nameAr: "بنما",
    iso3Code: "PAN",
  ),
  Country(
    isoCode: "PG",
    phoneCode: "675",
    name: "Papua New Guinea",
    nameAr: "بابوا غينيا الجديدة",
    iso3Code: "PNG",
  ),
  Country(
    isoCode: "PY",
    phoneCode: "595",
    name: "Paraguay",
    nameAr: "باراغواي",
    iso3Code: "PRY",
  ),
  Country(
    isoCode: "PE",
    phoneCode: "51",
    name: "Peru",
    nameAr: "بيرو",
    iso3Code: "PER",
  ),
  Country(
    isoCode: "PH",
    phoneCode: "63",
    name: "Philippines",
    nameAr: "الفلبين",
    iso3Code: "PHL",
  ),
  Country(
    isoCode: "PN",
    phoneCode: "64",
    name: "Pitcairn",
    nameAr: "جزر بيتكيرن",
    iso3Code: "PCN",
  ),
  Country(
    isoCode: "PL",
    phoneCode: "48",
    name: "Poland",
    nameAr: "بولندا",
    iso3Code: "POL",
  ),
  Country(
    isoCode: "PT",
    phoneCode: "351",
    name: "Portugal",
    nameAr: "البرتغال",
    iso3Code: "PRT",
  ),
  Country(
    isoCode: "PR",
    phoneCode: "1-787",
    name: "Puerto Rico",
    nameAr: "بورتوريكو",
    iso3Code: "PRI",
  ),
  Country(
    isoCode: "QA",
    phoneCode: "974",
    name: "Qatar",
    nameAr: "قطر",
    iso3Code: "QAT",
  ),
  Country(
    isoCode: "RO",
    phoneCode: "40",
    name: "Romania",
    nameAr: "رومانيا",
    iso3Code: "ROU",
  ),
  Country(
    isoCode: "RU",
    phoneCode: "7",
    name: "Russian Federation",
    nameAr: "روسيا",
    iso3Code: "RUS",
  ),
  Country(
    isoCode: "RW",
    phoneCode: "250",
    name: "Rwanda",
    nameAr: "رواندا",
    iso3Code: "RWA",
  ),
  Country(
    isoCode: "RE",
    phoneCode: "262",
    name: "Réunion",
    nameAr: "ريونيون",
    iso3Code: "REU",
  ),
  Country(
    isoCode: "BL",
    phoneCode: "590",
    name: "Saint Barthélemy",
    nameAr: "سان بارتيلمي",
    iso3Code: "BLM",
  ),
  Country(
    isoCode: "SH",
    phoneCode: "290",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    nameAr: "سانت هيلينا",
    iso3Code: "SHN",
  ),
  Country(
    isoCode: "KN",
    phoneCode: "1-869",
    name: "Saint Kitts and Nevis",
    nameAr: "سانت كيتس ونيفيس",
    iso3Code: "KNA",
  ),
  Country(
    isoCode: "LC",
    phoneCode: "1-758",
    name: "Saint Lucia",
    nameAr: "سانت لوسيا",
    iso3Code: "LCA",
  ),
  Country(
    isoCode: "MF",
    phoneCode: "590",
    name: "Saint Martin",
    nameAr: "سانت مارتن",
    iso3Code: "MAF",
  ),
  Country(
    isoCode: "PM",
    phoneCode: "508",
    name: "Saint Pierre and Miquelon",
    nameAr: "سان بيير وميكلون",
    iso3Code: "SPM",
  ),
  Country(
    isoCode: "VC",
    phoneCode: "1-784",
    name: "Saint Vincent and the Grenadines",
    nameAr: "سانت فنسنت والغرينادين",
    iso3Code: "VCT",
  ),
  Country(
    isoCode: "WS",
    phoneCode: "685",
    name: "Samoa",
    nameAr: "ساموا",
    iso3Code: "WSM",
  ),
  Country(
    isoCode: "SM",
    phoneCode: "378",
    name: "San Marino",
    nameAr: "سان مارينو",
    iso3Code: "SMR",
  ),
  Country(
    isoCode: "ST",
    phoneCode: "239",
    name: "Sao Tome and Principe",
    nameAr: "ساو تومي وبرينسيبي",
    iso3Code: "STP",
  ),
  Country(
    isoCode: "GB-SCT",
    phoneCode: "44",
    name: "Scotland",
    nameAr: "اسكتلندا",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "SN",
    phoneCode: "221",
    name: "Senegal",
    nameAr: "السنغال",
    iso3Code: "SEN",
  ),
  Country(
    isoCode: "RS",
    phoneCode: "381",
    name: "Serbia",
    nameAr: "صربيا",
    iso3Code: "SRB",
  ),
  Country(
    isoCode: "SC",
    phoneCode: "248",
    name: "Seychelles",
    nameAr: "سيشل",
    iso3Code: "SYC",
  ),
  Country(
    isoCode: "SL",
    phoneCode: "232",
    name: "Sierra Leone",
    nameAr: "سيراليون",
    iso3Code: "SLE",
  ),
  Country(
    isoCode: "SG",
    phoneCode: "65",
    name: "Singapore",
    nameAr: "سنغافورة",
    iso3Code: "SGP",
  ),
  Country(
    isoCode: "SX",
    phoneCode: "1-721",
    name: "Sint Maarten (Dutch part)",
    nameAr: "سينت مارتن",
    iso3Code: "SXM",
  ),
  Country(
    isoCode: "SK",
    phoneCode: "421",
    name: "Slovakia",
    nameAr: "سلوفاكيا",
    iso3Code: "SVK",
  ),
  Country(
    isoCode: "SI",
    phoneCode: "386",
    name: "Slovenia",
    nameAr: "سلوفينيا",
    iso3Code: "SVN",
  ),
  Country(
    isoCode: "SB",
    phoneCode: "677",
    name: "Solomon Islands",
    nameAr: "جزر سليمان",
    iso3Code: "SLB",
  ),
  Country(
    isoCode: "SO",
    phoneCode: "252",
    name: "Somalia",
    nameAr: "الصومال",
    iso3Code: "SOM",
  ),
  Country(
    isoCode: "ZA",
    phoneCode: "27",
    name: "South Africa",
    nameAr: "جنوب أفريقيا",
    iso3Code: "ZAF",
  ),
  Country(
    isoCode: "GS",
    phoneCode: "500",
    name: "South Georgia and the South Sandwich Islands",
    nameAr: "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
    iso3Code: "SGS",
  ),
  Country(
    isoCode: "SS",
    phoneCode: "211",
    name: "South Sudan",
    nameAr: "جنوب السودان",
    iso3Code: "SSD",
  ),
  Country(
    isoCode: "ES",
    phoneCode: "34",
    name: "Spain",
    nameAr: "إسبانيا",
    iso3Code: "ESP",
  ),
  Country(
    isoCode: "LK",
    phoneCode: "94",
    name: "Sri Lanka",
    nameAr: "سريلانكا",
    iso3Code: "LKA",
  ),
  Country(
    isoCode: "SD",
    phoneCode: "249",
    name: "Sudan",
    nameAr: "السودان",
    iso3Code: "SDN",
  ),
  Country(
    isoCode: "SR",
    phoneCode: "597",
    name: "Suriname",
    nameAr: "سورينام",
    iso3Code: "SUR",
  ),
  Country(
    isoCode: "SJ",
    phoneCode: "47",
    name: "Svalbard and Jan Mayen Islands",
    nameAr: "سفالبارد ويان ماين",
    iso3Code: "SJM",
  ),
  Country(
    isoCode: "SZ",
    phoneCode: "268",
    name: "Swaziland",
    nameAr: "إسواتيني",
    iso3Code: "SWZ",
  ),
  Country(
    isoCode: "SE",
    phoneCode: "46",
    name: "Sweden",
    nameAr: "السويد",
    iso3Code: "SWE",
  ),
  Country(
    isoCode: "CH",
    phoneCode: "41",
    name: "Switzerland",
    nameAr: "سويسرا",
    iso3Code: "CHE",
  ),
  Country(
    isoCode: "SY",
    phoneCode: "963",
    name: "Syrian Arab Republic",
    nameAr: "سوريا",
    iso3Code: "SYR",
  ),
  Country(
    isoCode: "TW",
    phoneCode: "886",
    name: "Taiwan",
    nameAr: "تايوان",
    iso3Code: "TWN",
  ),
  Country(
    isoCode: "TJ",
    phoneCode: "992",
    name: "Tajikistan",
    nameAr: "طاجيكستان",
    iso3Code: "TJK",
  ),
  Country(
    isoCode: "TZ",
    phoneCode: "255",
    name: "Tanzania, United Republic of",
    nameAr: "تنزانيا",
    iso3Code: "TZA",
  ),
  Country(
    isoCode: "TH",
    phoneCode: "66",
    name: "Thailand",
    nameAr: "تايلاند",
    iso3Code: "THA",
  ),
  Country(
    isoCode: "TL",
    phoneCode: "670",
    name: "Timor-Leste",
    nameAr: "تيمور الشرقية",
    iso3Code: "TLS",
  ),
  Country(
    isoCode: "TG",
    phoneCode: "228",
    name: "Togo",
    nameAr: "توغو",
    iso3Code: "TGO",
  ),
  Country(
    isoCode: "TK",
    phoneCode: "690",
    name: "Tokelau",
    nameAr: "توكيلاو",
    iso3Code: "TKL",
  ),
  Country(
    isoCode: "TO",
    phoneCode: "676",
    name: "Tonga",
    nameAr: "تونغا",
    iso3Code: "TON",
  ),
  Country(
    isoCode: "TT",
    phoneCode: "1-868",
    name: "Trinidad and Tobago",
    nameAr: "ترينيداد وتوباغو",
    iso3Code: "TTO",
  ),
  Country(
    isoCode: "TN",
    phoneCode: "216",
    name: "Tunisia",
    nameAr: "تونس",
    iso3Code: "TUN",
  ),
  Country(
    isoCode: "TR",
    phoneCode: "90",
    name: "Turkey",
    nameAr: "تركيا",
    iso3Code: "TUR",
  ),
  Country(
    isoCode: "TM",
    phoneCode: "993",
    name: "Turkmenistan",
    nameAr: "تركمانستان",
    iso3Code: "TKM",
  ),
  Country(
    isoCode: "TC",
    phoneCode: "1-649",
    name: "Turks and Caicos Islands",
    nameAr: "جزر توركس وكايكوس",
    iso3Code: "TCA",
  ),
  Country(
    isoCode: "TV",
    phoneCode: "688",
    name: "Tuvalu",
    nameAr: "توفالو",
    iso3Code: "TUV",
  ),
  Country(
    isoCode: "UG",
    phoneCode: "256",
    name: "Uganda",
    nameAr: "أوغندا",
    iso3Code: "UGA",
  ),
  Country(
    isoCode: "UA",
    phoneCode: "380",
    name: "Ukraine",
    nameAr: "أوكرانيا",
    iso3Code: "UKR",
  ),
  Country(
    isoCode: "AE",
    phoneCode: "971",
    name: "United Arab Emirates",
    nameAr: "الإمارات العربية المتحدة",
    iso3Code: "ARE",
  ),
  Country(
    isoCode: "GB",
    phoneCode: "44",
    name: "United Kingdom",
    nameAr: "المملكة المتحدة",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "US",
    phoneCode: "1",
    name: "United States",
    nameAr: "الولايات المتحدة الأمريكية",
    iso3Code: "USA",
  ),
  Country(
    isoCode: "UY",
    phoneCode: "598",
    name: "Uruguay",
    nameAr: "الأوروغواي",
    iso3Code: "URY",
  ),
  Country(
    isoCode: "UM",
    phoneCode: "1",
    name: "US Minor Outlying Islands",
    nameAr: "جزر الولايات المتحدة الصغيرة النائية",
    iso3Code: "UMI",
  ),
  Country(
    isoCode: "UZ",
    phoneCode: "998",
    name: "Uzbekistan",
    nameAr: "أوزبكستان",
    iso3Code: "UZB",
  ),
  Country(
    isoCode: "VU",
    phoneCode: "678",
    name: "Vanuatu",
    nameAr: "فانواتو",
    iso3Code: "VUT",
  ),
  Country(
    isoCode: "VE",
    phoneCode: "58",
    name: "Venezuela, Bolivarian Republic of",
    nameAr: "فنزويلا",
    iso3Code: "VEN",
  ),
  Country(
    isoCode: "VN",
    phoneCode: "84",
    name: "Vietnam",
    nameAr: "فيتنام",
    iso3Code: "VNM",
  ),
  Country(
    isoCode: "VG",
    phoneCode: "1-284",
    name: "Virgin Islands, British",
    nameAr: "جزر العذراء البريطانية",
    iso3Code: "VGB",
  ),
  Country(
    isoCode: "VI",
    phoneCode: "1-340",
    name: "Virgin Islands, U.S.",
    nameAr: "جزر العذراء الأمريكية",
    iso3Code: "VIR",
  ),
  Country(
    isoCode: "GB-WLS",
    phoneCode: "44",
    name: "Wales",
    nameAr: "ويلز",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "WF",
    phoneCode: "681",
    name: "Wallis and Futuna Islands",
    nameAr: "جزر واليس وفوتونا",
    iso3Code: "WLF",
  ),
  Country(
    isoCode: "EH",
    phoneCode: "212",
    name: "Western Sahara",
    nameAr: "الصحراء الغربية",
    iso3Code: "ESH",
  ),
  Country(
    isoCode: "YE",
    phoneCode: "967",
    name: "Yemen",
    nameAr: "اليمن",
    iso3Code: "YEM",
  ),
  Country(
    isoCode: "ZM",
    phoneCode: "260",
    name: "Zambia",
    nameAr: "زامبيا",
    iso3Code: "ZMB",
  ),
  Country(
    isoCode: "ZW",
    phoneCode: "263",
    name: "Zimbabwe",
    nameAr: "زيمبابوي",
    iso3Code: "ZWE",
  ),
  Country(
    isoCode: "AX",
    phoneCode: "358",
    name: "Åland Islands",
    nameAr: "جزر أولاند",
    iso3Code: "ALA",
  ),
];
